import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { BottomBar } from "@/components/BottomBar";
import { cn } from "@/utils";
import { AuthUserProvider } from "@/context/auth.context";
import { Theme } from "react-daisyui";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { ThemeWrapper } from "@/components/Theme";
import { SessionProvider } from "next-auth/react";
import SessionWrapper from "@/components/SessionWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Medtime",
  description: "Generated by Medtime",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionWrapper>
      <html lang="pt-BR">
        <head>
          <link rel="manifest" href="/manifest.json" />
        </head>
        <body className={cn(inter.className, "h-screen")}>
          <ThemeWrapper>{children}</ThemeWrapper>
        </body>
      </html>
    </SessionWrapper>
  );
}
