import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils";
// import { ThemeProvider } from "../components/theme/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Medtime",
  description: "Generated by Medtime",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="pt-BR" suppressHydrationWarning={true} >
        <head>
          <link rel="manifest" href="/manifest.json" />
        </head>
        <body suppressHydrationWarning={true} className={cn(inter.className, "h-screen overflow-hidden")}>
          {/* <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          > */}
            <div className="flex h-full flex-col items-center justify-center">
              {children}
            </div>
          {/* </ThemeProvider> */}
        </body>
      </html>
  );
}
