import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: "Medtime - Novo Medicamento",
  description: "Generated by Medtime",
}
const layout = (props:any) => {
  return (
      props.children 
  );
}

export default layout;